// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPHuceu_sNjqxyhO_Nw1kFvdZof4aX3hU',
    appId: '1:452384991723:web:89190194346a4f0b1911ae',
    messagingSenderId: '452384991723',
    projectId: 'ddm-project-32430',
    authDomain: 'ddm-project-32430.firebaseapp.com',
    storageBucket: 'ddm-project-32430.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd9M0myNLs4cf0fym6YpyeFjECLkQCSpI',
    appId: '1:452384991723:android:16949e0b9d0c71541911ae',
    messagingSenderId: '452384991723',
    projectId: 'ddm-project-32430',
    storageBucket: 'ddm-project-32430.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlltmKRBZZDpxFmZagg-vsQwPY3xiG1Pw',
    appId: '1:452384991723:ios:2bd6ab483d5918e21911ae',
    messagingSenderId: '452384991723',
    projectId: 'ddm-project-32430',
    storageBucket: 'ddm-project-32430.firebasestorage.app',
    iosBundleId: 'com.example.ddm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlltmKRBZZDpxFmZagg-vsQwPY3xiG1Pw',
    appId: '1:452384991723:ios:2bd6ab483d5918e21911ae',
    messagingSenderId: '452384991723',
    projectId: 'ddm-project-32430',
    storageBucket: 'ddm-project-32430.firebasestorage.app',
    iosBundleId: 'com.example.ddm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPHuceu_sNjqxyhO_Nw1kFvdZof4aX3hU',
    appId: '1:452384991723:web:39d02f125b0a71031911ae',
    messagingSenderId: '452384991723',
    projectId: 'ddm-project-32430',
    authDomain: 'ddm-project-32430.firebaseapp.com',
    storageBucket: 'ddm-project-32430.firebasestorage.app',
  );
}
